### ISSUE TITLE
Issues trying to use this theme

### ISSUE THREAD

**Issue by kirilyuro** [czottmann/yuidoc-theme-dana#16]
Default theme works great, but when trying using this theme instead the "Default" its throws errors as shown below:
![dana issue](https://cloud.githubusercontent.com/assets/13638485/10576704/fc55803a-766d-11e5-8de1-1db488f04051.png)
Please provide solution

**Comment by czottmann** [comment]
No, sorry, can't.  I haven't used YUIDoc in ~5 years, this project is abandoned.  Feel free to fork and fix it yourself, tho.  :)
