### ISSUE TITLE
Error generating API page

### ISSUE THREAD

**Issue by swalkinshaw** [czottmann/yuidoc-theme-dana#9]
Note: I'm not using the C version of NameMapper if that matters.

Got YUI Doc working perfectly with default template. Switched to this one and I get the following error:

```
INFO:  Generating API page for WeatherWidget
Traceback (most recent call last):
  File "/home/scott/yuidoc/bin/yuidoc.py", line 104, in <module>
    main()
  File "/home/scott/yuidoc/bin/yuidoc.py", line 99, in main
    gen.process()
  File "/home/scott/yuidoc/bin/yuidoc_generate.py", line 567, in process
    self.write("%s.html" %(self.classname), t)
  File "/home/scott/yuidoc/bin/yuidoc_generate.py", line 104, in write
    out.writelines(str(data))
  File "/usr/lib/python2.5/site-packages/Cheetah-2.4.2.1-py2.5.egg/Cheetah/Template.py", line 1005, in __str__
    rc = getattr(self, mainMethName)()
  File "_home_scott_yuidoc_templates_dana_main_tmpl.py", line 266, in respond
  File "/usr/lib/python2.5/site-packages/Cheetah-2.4.2.1-py2.5.egg/Cheetah/NameMapper.py", line 246, in valueFromSearchList
    _raiseNotFoundException(key, searchList)
  File "/usr/lib/python2.5/site-packages/Cheetah-2.4.2.1-py2.5.egg/Cheetah/NameMapper.py", line 167, in _raiseNotFoundException
    raise NotFound(excString)
Cheetah.NameMapper.NotFound: cannot find 'cleansedmodulenames'
```

**Comment by swalkinshaw** [comment]
Installed the version of Cheetah with the C compiled NameMapper and the error still occurs.

**Comment by swalkinshaw** [comment]
I found a few other errors too. If I had to guess, it looks like you edited .py files as well but those aren't included in this theme.

**Comment by czottmann** [comment]
Actually, no, I've tried it with several versions of YUIDoc (patched for Markdown support, unpatched), including the latest official git clone'd from github.com/yui/yuidoc — no problems.

Nonetheless, it doesn't seem to work for you, so something's wrong.  Let's start by comparing dependencies versions, shall we?

```
➜ yolk -l | grep -iE "simplejson|pygments|cheetah"
Cheetah         - 2.4.2.1      - active 
Pygments        - 1.3.1        - active 
simplejson      - 2.1.0        - active 
```

**Comment by swalkinshaw** [comment]
YUI Docs v1.0.0b1 (from the YUI Library page)

```
➜ yolk -l | grep -iE "simplejson|pygments|cheetah"
Cheetah         - 2.4.2.1      - active
Pygments      - 1.3.1        - active
simplejson      - 2.1.1         - active
```

**Comment by czottmann** [comment]
Which version of Python?

**Comment by swalkinshaw** [comment]
Python 2.5.2

Here's the sh script I'm using:

```
#!/bin/sh
DIR=/home/scott
yuidoc_home=$DIR/yuidoc
parser_in="$DIR/js-yui/core $DIR/js-yui/widgets"
parser_out=$DIR/docs/parser
generator_out=$DIR/docs/generator
template=$yuidoc_home/templates/dana
version=1.0.0
yuiversion=3
python $yuidoc_home/bin/yuidoc.py $parser_in -p $parser_out -o $generator_out -t $template -v $version -Y $yuiversion
```

**Comment by swalkinshaw** [comment]
In case this helps, if I fix that error by removing the reference to 'cleansedmodulenames'. I get a similar "cant find" error for $copyrighttag and 'highlightcontent' as well.

**Comment by cayasso** [comment]
Carlo, I am having the exact same issue described by swalkinshaw, I am using Python 2.5.2 on Ubuntu 10

<pre>
Cheetah         - 2.4.2.1      - active 
Pygments        - 1.3.1        - active
simplejson      - 2.0.9        - non-active 
simplejson      - 2.1.1        - active 
</pre>


Thank you for the help in advance!

**Comment by czottmann** [comment]
Hi guys, I finally had some time to look into this, and I was able to reproduce the issue.  Here's the fun part: it only occurs with YUIDoc v1.0.0b1.  If you'd get the latest build of YUIDoc (or the its `master` branch) there'd be no problems.

It appears that between the last official release (v1.0.0b1) and the latest build the YUI guys introduced some new template variables, which Dana is making use of.  The more you know…

I've not decided whether or not I'll update the theme, given that the official release is almost 2 years old by now, and there've been a lot of builds since then.

**Comment by cayasso** [comment]
Yup that was is, it is working now, yeee eeeee!!!!!!!

Thank you Carlo!

**Comment by czottmann** [comment]
Very welcome. :)

**Comment by swalkinshaw** [comment]
Working great now. Thanks!
